name: Secret Scan

on:
  push:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run secret scan
        shell: bash
        run: |
          bash .github/scripts/secret_scan.sh

